import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
import * as Crypto from 'expo-crypto';
import { captureLocation, type CapturedLocation } from '../lib/location';
import { classifyLocally, materialLabels, type MaterialLabel } from '../lib/classifier';
import { enqueueLot, persistImage } from '../lib/offline';

type Tab = 'Home' | 'Lots' | 'Create Lot' | 'Offers' | 'Earnings' | 'Safety' | 'Profile';

export default function CollectorHome() {
  const [tab, setTab] = useState<Tab>('Home'); const [photo, setPhoto] = useState<string>(); const [material, setMaterial] = useState<MaterialLabel>('pcb'); const [weight, setWeight] = useState(''); const [location, setLocation] = useState<CapturedLocation>(); const [saving, setSaving] = useState(false);
  const takePhoto = async () => { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) return Alert.alert('Camera permission', 'Choose a photo from the gallery instead.'); const result = await ImagePicker.launchCameraAsync({ quality: 0.65, mediaTypes: ['images'] }); if (result.canceled) return; const optimized = await ImageManipulator.manipulateAsync(result.assets[0].uri, [{ resize: { width: 1280 } }], { compress: 0.7, format: ImageManipulator.SaveFormat.JPEG }); setPhoto(optimized.uri); const prediction = await classifyLocally(optimized.uri); if (prediction) setMaterial(prediction.material); };
  const saveOffline = async () => { if (!photo || !weight || !location) return Alert.alert('Complete the lot', 'Add a photo, weight and location first.'); setSaving(true); try { const localPhoto = await persistImage(photo); await enqueueLot({ client_uuid: Crypto.randomUUID(), material_category: material, estimated_weight_kg: Number(weight), condition: 'good', location: { lat: location.lat, lng: location.lng }, image_uris: [localPhoto], created_at: new Date().toISOString() }); Alert.alert('Saved safely', 'This lot and photo are kept on the device until sync is available.'); setTab('Home'); } catch (error) { Alert.alert('Could not save', error instanceof Error ? error.message : 'Please try again.'); } finally { setSaving(false); } };
  return <View style={styles.page}><View style={styles.header}><Text style={styles.brand}>♻ KabadiConnect</Text><Text style={styles.subBrand}>कबाड़ी कनेक्ट</Text></View><ScrollView contentContainerStyle={styles.content}>{tab === 'Create Lot' ? <><Text style={styles.eyebrow}>CREATE LOT</Text><Text style={styles.heading}>Make a new e-waste lot</Text><Pressable style={styles.photo} onPress={() => void takePhoto()}>{photo ? <Image source={{ uri: photo }} style={styles.image} /> : <Text style={styles.photoText}>📷 Take photo</Text>}</Pressable><Text style={styles.label}>Material (confirm or change)</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.materials}>{materialLabels.map(item => <Pressable key={item} style={[styles.material, material === item && styles.selected]} onPress={() => setMaterial(item)}><Text style={material === item ? styles.selectedText : undefined}>{item.replace('_', ' ')}</Text></Pressable>)}</ScrollView><Text style={styles.label}>Approximate weight (kg)</Text><TextInput style={styles.input} inputMode="decimal" value={weight} onChangeText={setWeight} placeholder="e.g. 12.5" /><Pressable style={styles.location} onPress={() => void captureLocation().then(setLocation).catch(error => Alert.alert('Location unavailable', error.message))}><Text>{location ? '✓ Location captured' : '⌖ Capture location'}</Text></Pressable><Pressable style={styles.primary} disabled={saving} onPress={() => void saveOffline()}><Text style={styles.primaryText}>{saving ? 'Saving…' : 'Save safely on device'}</Text></Pressable><Text style={styles.note}>Manual material selection is always available. A low-confidence or unavailable model never blocks this flow.</Text></> : <><Text style={styles.eyebrow}>{tab.toUpperCase()}</Text><Text style={styles.heading}>{tab === 'Home' ? 'Hello, collector' : tab}</Text><View style={styles.card}><Text style={styles.cardTitle}>{tab === 'Home' ? 'Create a lot even without internet' : 'This native screen is ready for the API-backed workflow.'}</Text><Text style={styles.note}>Large touch controls, on-device image persistence, and permission-aware location capture are enabled for the lot flow.</Text></View></>}</ScrollView><ScrollView horizontal style={styles.tabs} contentContainerStyle={styles.tabContent} showsHorizontalScrollIndicator={false}>{(['Home','Lots','Create Lot','Offers','Earnings','Safety','Profile'] as Tab[]).map(item => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.activeTab]}><Text style={tab === item ? styles.activeTabText : undefined}>{item}</Text></Pressable>)}</ScrollView></View>;
}
const styles = StyleSheet.create({ page:{flex:1,backgroundColor:'#fafaf4'},header:{padding:20,paddingTop:54,backgroundColor:'#fff',borderBottomWidth:1,borderColor:'#e3e3de'},brand:{fontSize:21,fontWeight:'900',color:'#0c5216'},subBrand:{fontSize:11,color:'#687167'},content:{padding:20,paddingBottom:100},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1,color:'#0c5216'},heading:{fontSize:28,fontWeight:'800',marginTop:4,marginBottom:20,color:'#1a1c19'},photo:{minHeight:160,borderWidth:2,borderStyle:'dashed',borderColor:'#91d78a',borderRadius:16,alignItems:'center',justifyContent:'center',overflow:'hidden'},photoText:{fontSize:17,fontWeight:'800',color:'#0c5216'},image:{height:190,width:'100%',resizeMode:'cover'},label:{fontSize:14,fontWeight:'800',marginTop:18,marginBottom:8},materials:{gap:8},material:{padding:10,backgroundColor:'#eeeee9',borderRadius:8},selected:{backgroundColor:'#1b5e20'},selectedText:{color:'#fff',fontWeight:'800'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#c0c9bb',borderRadius:10,padding:14,fontSize:18},location:{marginTop:14,padding:15,borderRadius:10,backgroundColor:'#d6e3ff'},primary:{marginTop:14,padding:16,borderRadius:10,backgroundColor:'#1b5e20',alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900',fontSize:16},note:{color:'#687167',fontSize:13,lineHeight:19,marginTop:12},card:{padding:20,borderRadius:16,backgroundColor:'#fff'},cardTitle:{fontSize:18,fontWeight:'800'},tabs:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'#fff',borderTopWidth:1,borderColor:'#e3e3de'},tabContent:{padding:8,gap:6},tab:{paddingVertical:10,paddingHorizontal:12,borderRadius:8},activeTab:{backgroundColor:'#e1f3df'},activeTabText:{color:'#0c5216',fontWeight:'800'} });
