import { StrictMode, useEffect, useMemo, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import { api, ApiError, saveSession, session } from './api';
import { connectRealtime } from './realtime';
import type { Lot, LotDraft, Material, Offer, Payment, Price, Session, TraceEvent, Transaction } from './types';
import './styles.css';

const materials: Material[] = ['pcb', 'cable', 'battery', 'lcd_panel', 'crt', 'motor', 'magnet_assembly', 'mixed_plastic', 'other'];
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, char => char.toUpperCase());
const money = (value?: string | null) => value ? `₹${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 2 })}` : '—';
const uuid = () => crypto.randomUUID();
const offlineKey = 'kc-pending-lots';
const getQueue = () => JSON.parse(localStorage.getItem(offlineKey) || '[]') as LotDraft[];
const queue = (draft: LotDraft) => localStorage.setItem(offlineKey, JSON.stringify([...getQueue(), draft]));
type Coordinates = { lat: number; lng: number };
const captureBrowserLocation = () => new Promise<Coordinates>((resolve, reject) => {
  if (!navigator.geolocation) return reject(new Error('Location is unavailable in this browser.'));
  navigator.geolocation.getCurrentPosition(
    position => resolve({ lat: position.coords.latitude, lng: position.coords.longitude }),
    () => reject(new Error('Location permission is required to continue.')),
    { enableHighAccuracy: true, maximumAge: 0, timeout: 10000 },
  );
});

function Alert({ children, error = false }: { children: React.ReactNode; error?: boolean }) { return <p className={error ? 'alert error' : 'alert'}>{children}</p>; }
function Loading() { return <div className="loading">Loading your live workspace…</div>; }

function Login({ onSignedIn }: { onSignedIn: (value: Session) => void }) {
  const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [requested, setRequested] = useState(false); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { if (!requested) { await api.requestOtp(phone); setRequested(true); setMessage('OTP sent. For local mock authentication, use 123456.'); } else { const value = await api.verifyOtp(phone, otp); saveSession(value); onSignedIn(value); } } catch (error) { setMessage(error instanceof Error ? error.message : 'Sign-in failed.'); } finally { setBusy(false); } };
  return <main className="login"><section className="login-card"><div className="brand-mark">♻</div><p className="eyebrow">SAFE E-WASTE MARKETPLACE</p><h1>Kabadi<span>Connect</span></h1><p className="muted">A trusted way to sell, collect, and recycle electronics.</p><form onSubmit={submit}><label>Mobile number<input required type="tel" value={phone} onChange={e => setPhone(e.target.value)} placeholder="+91 99999 99999" /></label>{requested && <label>One-time password<input required inputMode="numeric" value={otp} onChange={e => setOtp(e.target.value)} placeholder="Enter OTP" /></label>}<button className="primary full" disabled={busy}>{busy ? 'Please wait…' : requested ? 'Secure sign in' : 'Send OTP'}</button></form>{message && <Alert error={!message.startsWith('OTP sent')}>{message}</Alert>}<small>Access is role-aware. Your account opens the collector or recycler workspace automatically.</small></section></main>;
}

function Collector({ onLogout }: { onLogout: () => void }) {
  const [lots, setLots] = useState<Lot[]>([]); const [prices, setPrices] = useState<Price[]>([]); const [earnings, setEarnings] = useState<string>(); const [tab, setTab] = useState<'home' | 'create' | 'offers' | 'history'>('home'); const [error, setError] = useState(''); const [offline, setOffline] = useState(!navigator.onLine);
  const refresh = async () => { try { const [myLots, currentPrices, earned] = await Promise.all([api.lots(), api.prices(), api.earnings()]); setLots(myLots.items); setPrices(currentPrices.items); setEarnings(earned.total_earned_inr); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load dashboard.'); } };
  useEffect(() => { void refresh(); const update = () => setOffline(!navigator.onLine); addEventListener('online', update); addEventListener('offline', update); const disconnect = connectRealtime(() => void refresh()); return () => { removeEventListener('online', update); removeEventListener('offline', update); disconnect(); }; }, []);
  const sync = async () => { const pending = getQueue(); if (!pending.length) return; try { await api.syncLots(pending); localStorage.removeItem(offlineKey); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Sync failed. Your lot is still safely queued.'); } };
  return <main className="collector"><header className="mobile-header"><div><span className="logo">♻</span><b>KabadiConnect</b><small>कबाड़ी कनेक्ट</small></div><button className="quiet" onClick={onLogout}>Log out</button></header>{offline && <Alert error>You’re offline. New lots will be kept safely and synced later.</Alert>}{getQueue().length > 0 && <button className="sync" onClick={() => void sync()}>↻ Sync {getQueue().length} pending lot{getQueue().length > 1 ? 's' : ''}</button>}
    {tab === 'home' && <CollectorHome lots={lots} prices={prices} earnings={earnings} onCreate={() => setTab('create')} onOffers={() => setTab('offers')} error={error} retry={refresh} />}
    {tab === 'create' && <CreateLot done={() => { setTab('home'); void refresh(); }} />}
    {tab === 'offers' && <Offers lots={lots} />}
    {tab === 'history' && <section className="collector-content"><p className="eyebrow">EARNINGS & HISTORY</p><h2>Your pickups and payments</h2><TransactionWorkspace initial={[]} refresh={refresh} role="collector" /></section>}
    <nav className="bottom-nav"><button className={tab === 'home' ? 'active' : ''} onClick={() => setTab('home')}>⌂<span>Home</span></button><button className={tab === 'create' ? 'active' : ''} onClick={() => setTab('create')}>＋<span>New lot</span></button><button className={tab === 'offers' ? 'active' : ''} onClick={() => setTab('offers')}>▣<span>Offers</span></button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>₹<span>History</span></button></nav></main>;
}
function CollectorHome({ lots, prices, earnings, onCreate, onOffers, error, retry }: { lots: Lot[]; prices: Price[]; earnings?: string; onCreate: () => void; onOffers: () => void; error: string; retry: () => void }) { return <section className="collector-content"><p className="eyebrow">TODAY’S COLLECTION</p><h2>Hello, collector 👋</h2>{error && <Alert error>{error} <button className="link" onClick={retry}>Retry</button></Alert>}<div className="value-card"><span>My total earnings</span><strong>{money(earnings)}</strong><small>Paid transactions only</small></div><button className="primary create-cta" onClick={onCreate}>＋ Create a new e-waste lot</button><h3>Your lots</h3>{lots.length ? <div className="stack">{lots.slice(0, 4).map(lot => <article className="lot-card" key={lot.id}><div className="icon">{lot.material_category === 'battery' ? '▣' : '▤'}</div><div><b>{label(lot.material_category)}</b><small>{lot.estimated_weight_kg} kg · {label(lot.condition)}</small></div><span className="chip">{label(lot.status)}</span></article>)}</div> : <div className="empty">No lots yet. Tap the green button to create your first lot.</div>}<h3>Today’s indicative rates</h3><div className="rates">{prices.slice(0, 3).map(rate => <div key={rate.id}><b>{label(rate.material_category)}</b><span>{money(rate.market_range_low_inr_per_kg)}–{money(rate.market_range_high_inr_per_kg)}/kg</span></div>)}</div><button className="outline full" onClick={onOffers}>View offers on my lots</button></section>; }
function CreateLot({ done }: { done: () => void }) { const [step, setStep] = useState(1); const [material, setMaterial] = useState<Material>('pcb'); const [weight, setWeight] = useState(''); const [condition, setCondition] = useState<LotDraft['condition']>('good'); const [file, setFile] = useState<File>(); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const create = async () => { if (!weight || Number(weight) <= 0) return setNotice('Enter an approximate weight greater than zero.'); setBusy(true); let image_urls: string[] = []; let location: Coordinates; try { location = await captureBrowserLocation(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Location permission is required to continue.'); setBusy(false); return; } try { if (file && navigator.onLine) image_urls = [await api.upload(file)]; const draft: LotDraft = { client_uuid: uuid(), material_category: material, image_urls, estimated_weight_kg: Number(weight), weight_status: 'estimated', condition, source_type: 'household', location, created_by_actor: 'collector' }; if (!navigator.onLine) { queue(draft); setNotice('Saved offline. It will sync when you reconnect.'); return; } await api.createLot(draft); done(); } catch (e) { const draft: LotDraft = { client_uuid: uuid(), material_category: material, image_urls, estimated_weight_kg: Number(weight), weight_status: 'estimated', condition, source_type: 'household', location, created_by_actor: 'collector' }; queue(draft); setNotice(`${e instanceof Error ? e.message : 'Network issue'}. Saved safely for retry.`); } finally { setBusy(false); } };
  return <section className="collector-content"><button className="back" onClick={done}>← Back</button><p className="eyebrow">CREATE LOT · STEP {step} OF 3</p>{step === 1 && <><h2>Photo & material</h2><label className="photo"><input type="file" accept="image/*" onChange={e => setFile(e.target.files?.[0])} />{file ? `✓ ${file.name}` : '📷 Take or choose a photo'}</label><label>Material<select value={material} onChange={e => setMaterial(e.target.value as Material)}>{materials.map(item => <option value={item} key={item}>{label(item)}</option>)}</select></label><small>Choose manually if on-device material identification is unavailable.</small><button className="primary full" onClick={() => setStep(2)}>Continue</button></>}{step === 2 && <><h2>Weight & condition</h2><label>Approximate weight (kg)<input autoFocus inputMode="decimal" type="number" min="0.01" step="0.01" value={weight} onChange={e => setWeight(e.target.value)} placeholder="e.g. 12.5" /></label><div className="choices">{(['good', 'damaged', 'mixed'] as const).map(item => <button className={condition === item ? 'selected' : ''} onClick={() => setCondition(item)} key={item}>{label(item)}</button>)}</div><button className="primary full" onClick={() => setStep(3)}>See estimate</button></>}{step === 3 && <><h2>Review your lot</h2><div className="review"><b>{label(material)}</b><span>{weight} kg · {label(condition)}</span><small>Value shown after creation is an AI-assisted indicative estimate, not a guaranteed market price.</small></div><button className="primary full" disabled={busy} onClick={() => void create()}>{busy ? 'Creating safely…' : 'Create lot'}</button></>}{notice && <Alert error={notice.includes('Enter')}>{notice}</Alert>}</section>; }
function Offers({ lots }: { lots: Lot[] }) { const [selected, setSelected] = useState(lots[0]?.id || ''); const [offers, setOffers] = useState<Offer[]>([]); const [message, setMessage] = useState(''); useEffect(() => { if (selected) api.offers(selected).then(v => setOffers(v.items)).catch(e => setMessage(e.message)); }, [selected]); const accept = async (id: string) => { try { await api.acceptOffer(id); setOffers(current => current.map(offer => offer.id === id ? { ...offer, status: 'accepted' } : offer)); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to accept offer.'); } }; return <section className="collector-content"><p className="eyebrow">MARKETPLACE</p><h2>Offers on my lots</h2>{lots.length ? <><select value={selected} onChange={e => setSelected(e.target.value)}>{lots.map(lot => <option value={lot.id} key={lot.id}>{label(lot.material_category)} · {lot.estimated_weight_kg} kg</option>)}</select>{offers.length ? offers.map(offer => <article className="offer-card" key={offer.id}><b>{money(offer.offered_total_inr)}</b><span>{money(offer.offered_rate_inr_per_kg)}/kg · {offer.pickup_available ? 'Pickup available' : 'Self delivery'}</span><span className="chip">{offer.status}</span>{offer.status === 'pending' && <button className="primary" onClick={() => void accept(offer.id)}>Accept offer</button>}</article>) : <div className="empty">No offers yet. You’ll see authorized recycler offers here.</div>}</> : <div className="empty">Create a lot first to receive offers.</div>}{message && <Alert error>{message}</Alert>}</section>; }

function Recycler({ onLogout }: { onLogout: () => void }) { const [page, setPage] = useState<'dashboard' | 'lots' | 'transactions'>('dashboard'); const [lots, setLots] = useState<Lot[]>(); const [transactions, setTransactions] = useState<Transaction[]>(); const [error, setError] = useState(''); const load = async () => { try { const [open, tx] = await Promise.all([api.openLots(), api.transactions()]); setLots(open.items); setTransactions(tx.items); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load recycler data.'); } }; useEffect(() => { void load(); return connectRealtime(() => void load()); }, []); if (!lots || !transactions) return <Loading />; return <div className="recycler"><aside><div className="recycler-brand"><span>♻</span><div><b>KabadiConnect</b><small>RECYCLER OPS</small></div></div><p>ENTERPRISE PORTAL</p>{([['dashboard', '▦ Dashboard'], ['lots', '▤ Available lots'], ['transactions', '▣ Transactions']] as const).map(([id, title]) => <button key={id} className={page === id ? 'side-active' : ''} onClick={() => setPage(id)}>{title}</button>)}<div className="facility"><b>● Authorized facility</b><small>Only verified recyclers can submit offers.</small><button onClick={onLogout}>Secure sign out</button></div></aside><section className="recycler-main"><header><div><p className="eyebrow">CPCB-AWARE MARKETPLACE</p><h1>{page === 'dashboard' ? 'Operations dashboard' : page === 'lots' ? 'Available e-waste lots' : 'Transaction ledger'}</h1></div><button className="outline" onClick={() => void load()}>↻ Refresh live data</button></header>{error && <Alert error>{error}</Alert>}{page === 'dashboard' && <RecyclerDashboard lots={lots} transactions={transactions} onLots={() => setPage('lots')} />}{page === 'lots' && <Marketplace lots={lots} />}{page === 'transactions' && <Transactions transactions={transactions} refresh={load} />}</section></div>; }
function RecyclerDashboard({ lots, transactions, onLots }: { lots: Lot[]; transactions: Transaction[]; onLots: () => void }) { const active = transactions.filter(t => !['recycled', 'cancelled'].includes(t.status)); return <><div className="kpis"><Kpi label="Available lots" value={String(lots.length)} accent="green" /><Kpi label="Active transactions" value={String(active.length)} accent="blue" /><Kpi label="Pending handovers" value={String(active.filter(t => t.status === 'handed_over').length)} accent="orange" /><Kpi label="Recycled" value={String(transactions.filter(t => t.status === 'recycled').length)} accent="green" /></div><div className="panel"><div className="panel-title"><div><h2>Live regional marketplace</h2><p>Only open lots returned by the authorized backend service.</p></div><button className="primary" onClick={onLots}>Browse lots</button></div>{lots.length ? <LotTable lots={lots.slice(0, 5)} /> : <div className="empty">No open lots in your service area right now.</div>}</div><div className="panel"><h2>Recent lifecycle activity</h2>{transactions.length ? <div className="timeline">{transactions.slice(0, 5).map(t => <div key={t.id}><b>{label(t.status)}</b><span>Transaction {t.id.slice(0, 8)} · {new Date(t.updated_at).toLocaleString()}</span></div>)}</div> : <div className="empty">Accepted offers will appear here as active transactions.</div>}</div></> }
function Kpi({ label: text, value, accent }: { label: string; value: string; accent: string }) { return <div className={`kpi ${accent}`}><span>{text}</span><b>{value}</b><small>Live from API</small></div>; }
function LotTable({ lots, select }: { lots: Lot[]; select?: (lot: Lot) => void }) { return <div className="table-wrap"><table><thead><tr><th>Lot</th><th>Material</th><th>Weight</th><th>Condition</th><th>Indicative value</th><th>Status</th>{select && <th />}</tr></thead><tbody>{lots.map(lot => <tr key={lot.id}><td className="mono">{lot.id.slice(0, 8)}</td><td>{label(lot.material_category)}</td><td>{lot.estimated_weight_kg} kg</td><td>{label(lot.condition)}</td><td>{money(lot.estimated_value_total_inr)}</td><td><span className="chip">{label(lot.status)}</span></td>{select && <td><button className="small primary" onClick={() => select(lot)}>Make offer</button></td>}</tr>)}</tbody></table></div>; }
function Marketplace({ lots }: { lots: Lot[] }) { const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Lot>(); const filtered = useMemo(() => lots.filter(l => label(l.material_category).toLowerCase().includes(query.toLowerCase()) || l.id.includes(query)), [lots, query]); return <><div className="filters"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search lot ID or material" /><span>{filtered.length} lots available</span></div><div className="panel">{filtered.length ? <LotTable lots={filtered} select={setSelected} /> : <div className="empty">No lots match your search.</div>}</div>{selected && <OfferModal lot={selected} close={() => setSelected(undefined)} />}</>; }
function OfferModal({ lot, close }: { lot: Lot; close: () => void }) { const [rate, setRate] = useState(''); const [pickup, setPickup] = useState(true); const [message, setMessage] = useState(''); const total = rate && !Number.isNaN(Number(rate)) ? (Number(rate) * lot.estimated_weight_kg).toFixed(2) : '0.00'; const submit = async (event: FormEvent) => { event.preventDefault(); if (!rate || Number(rate) <= 0) return setMessage('Enter a valid rate per kg.'); try { await api.makeOffer(lot.id, { offered_rate_inr_per_kg: Number(rate).toFixed(2), offered_total_inr: total, pickup_available: pickup, expires_at: new Date(Date.now() + 72 * 3600_000).toISOString() }); close(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to submit offer.'); } }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button type="button" className="modal-close" onClick={close}>×</button><p className="eyebrow">MAKE A CONTRACTED OFFER</p><h2>{label(lot.material_category)} · {lot.estimated_weight_kg} kg</h2><label>Rate per kg (₹)<input required type="number" min="0.01" step="0.01" value={rate} onChange={e => setRate(e.target.value)} /></label><div className="offer-total">Total offered <b>₹{total}</b></div><label className="check"><input type="checkbox" checked={pickup} onChange={e => setPickup(e.target.checked)} /> Pickup available</label><small>The total is calculated from rate × contract weight. The backend validates it again.</small><button className="primary full">Submit offer</button>{message && <Alert error>{message}</Alert>}</form></div>; }
function Transactions({ transactions, refresh }: { transactions: Transaction[]; refresh: () => Promise<void> }) { return <TransactionWorkspace initial={transactions} refresh={refresh} role="recycler" />; }
function TransactionWorkspace({ initial, refresh, role }: { initial: Transaction[]; refresh: () => Promise<void>; role: 'collector' | 'recycler' }) {
  const [items, setItems] = useState(initial); const [selected, setSelected] = useState<Transaction>(); const [trace, setTrace] = useState<TraceEvent[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [message, setMessage] = useState(''); const [date, setDate] = useState(''); const [time, setTime] = useState('10:00 - 12:00'); const [place, setPlace] = useState(''); const [weight, setWeight] = useState(''); const [handoverFile, setHandoverFile] = useState<File>(); const [reference, setReference] = useState('');
  useEffect(() => { setItems(initial); if (!initial.length) api.transactions().then(result => setItems(result.items)).catch(error => setMessage(error.message)); }, [initial]);
  const detail = async (transaction: Transaction) => { setSelected(transaction); setMessage(''); try { const [events, paymentList] = await Promise.all([api.traceEvents(transaction.id), api.payments(transaction.id)]); setTrace(events.items); setPayments(paymentList.items); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load history.'); } };
  const run = async (action: () => Promise<unknown>) => { try { await action(); await refresh(); if (selected) await detail(selected); setMessage('Saved successfully.'); } catch (error) { setMessage(error instanceof ApiError ? error.message : 'Could not save. Please retry.'); } };
  if (!selected) return <div className="panel">{message && <Alert error>{message}</Alert>}{items.length ? <div className="transactions">{items.map(transaction => <article key={transaction.id}><button className="transaction-open" onClick={() => void detail(transaction)}><span className="mono">{transaction.id.slice(0, 8)}</span><b>{label(transaction.status)}</b><small>{money(transaction.final_total_inr)} · final {transaction.final_weight_kg ?? 'pending'} kg</small></button></article>)}</div> : <div className="empty">No transactions yet. Accepted offers appear here.</div>}</div>;
  return <div className="panel"><button className="back" onClick={() => setSelected(undefined)}>← All transactions</button><h2>{label(selected.status)}</h2><p className="muted">Final verified weight: <b>{selected.final_weight_kg ?? 'not verified'} kg</b> · final value {money(selected.final_total_inr)}</p>{message && <Alert error={!message.startsWith('Saved')}>{message}</Alert>}
    {selected.status === 'accepted' && <div className="workflow"><h3>Schedule pickup</h3><input type="date" value={date} onChange={event => setDate(event.target.value)} /><input value={time} onChange={event => setTime(event.target.value)} placeholder="Time window" /><input value={place} onChange={event => setPlace(event.target.value)} placeholder="Pickup location" /><button className="primary" disabled={!date || !place} onClick={() => void run(async () => { const location = await captureBrowserLocation(); return api.schedulePickup(selected.id, { client_uuid: uuid(), scheduled_date: date, scheduled_time_window: time, pickup_location: { ...location, label: place }, ...(role === 'collector' ? { collector_note: '' } : { recycler_note: '' }) }); })}>Schedule pickup</button></div>}
    {role === 'recycler' && selected.status === 'pickup_scheduled' && <div className="workflow"><h3>Verified-weight handover</h3><input type="number" inputMode="decimal" min="0.01" step="0.01" value={weight} onChange={event => setWeight(event.target.value)} placeholder="Verified weight (kg)" /><input type="file" accept="image/*" onChange={event => setHandoverFile(event.target.files?.[0])} /><button className="primary" disabled={Number(weight) <= 0 || !handoverFile} onClick={() => void run(async () => { const location = await captureBrowserLocation(); const photo = await api.upload(handoverFile!); return api.handover(selected.id, { client_uuid: uuid(), verified_weight_kg: Number(weight), timestamp: new Date().toISOString(), gps: location, photo_urls: [photo] }); })}>Record handover</button></div>}
    {role === 'recycler' && selected.status === 'handed_over' && <div className="workflow"><h3>Confirm handover</h3>{trace.filter(event => event.handover_reference_code).map(event => <button key={event.id} className="primary" onClick={() => void run(() => api.confirmHandover(event.id, event.handover_reference_code!))}>Confirm {event.handover_reference_code}</button>)}</div>}
    {role === 'recycler' && selected.status === 'confirmed' && <div className="workflow"><h3>Record payment</h3><input value={reference} onChange={event => setReference(event.target.value)} placeholder="UPI / bank reference (optional for cash)" /><button className="primary" onClick={() => void run(() => api.recordPayment(selected.id, { client_uuid: uuid(), amount_inr: selected.final_total_inr || '0.00', method: reference ? 'upi' : 'cash', status: reference ? 'upi_paid' : 'cash_collected', reference: reference || null, confirmed_by_collector: false, confirmed_by_recycler: true }))}>Record payment</button></div>}
    {role === 'recycler' && selected.status === 'paid' && <button className="primary" onClick={() => void run(() => api.transition(selected.id, 'recycled'))}>Mark recycled</button>}
    <h3>Traceability</h3><div className="timeline">{trace.length ? trace.map(event => <div key={event.id}><b>{label(event.event_type)}</b><span>{new Date(event.timestamp).toLocaleString()} · {event.recorded_by}</span></div>) : <div className="empty">No trace events yet.</div>}</div><h3>Payment history</h3>{payments.length ? payments.map(payment => <article className="offer-card" key={payment.id}><b>{money(payment.amount_inr)}</b><span>{label(payment.status)} · {label(payment.method)}</span><small>{payment.reference || 'No reference'} · {new Date(payment.recorded_at).toLocaleDateString()}</small></article>) : <div className="empty">No payment recorded yet.</div>}</div>;
}
function App() { const [current, setCurrent] = useState(session()); const logout = () => { saveSession(null); setCurrent(null); }; if (!current) return <Login onSignedIn={setCurrent} />; return current.role === 'collector' ? <Collector onLogout={logout} /> : <Recycler onLogout={logout} />; }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
